### ISSUE TITLE
Peer Review from Guangyu Liu

### ISSUE THREAD

**Issue by guangyu-liu** [uc-cfss/viz-dalyons3#1]
Hi Don and Nicole,

This is an interesting project! I assume your audience is the academia. In that case, scatter plots and box plots are nice choices to convey your results and your audiences are familiar with them. I also think you made a good balance between tables and graphs. The general trends are clear in graphs while keeping statistic details in the tables. You did a great job in sticking to truthfulness (choosing a separate column for each electrode rather than cortical average in the strip chart), and used visualization to exclude hazards due to small sample size (Asian/Pacific Rim group). In addition, I like the theme and text font you chose. The italic adjustment is beautiful and consistent. 

As a layperson of psychology, I have a few questions about the graphs – maybe they are not a problem in your discipline. (1) I agree that color and gradient are good choices to make graphs beautiful when displaying them in the screen, but I am not sure if they will be difficult to see in black-white printed thesis or journals. (2) The strip chart is actually a combination of strip chart and bar chart, using the latter to show the median of each column. I wonder if median is an important statistic in your analysis, box plot might provide more information than bar chart? Besides, the gray and transparent bar chart is a little bit difficult to see in the gray grids. (3) I was also wondering if violin chart will characterize the distribution better than strip chart. At the first sight, the columns of Fz and Pz look similar, but they have different medians, that might because of their different distribution? (4) In “Comparing Responses as a Function of Aggression”, as you said, one or two outliers caused a spike in the middle of the smooth line, while the line is mainly flat elsewhere. Did you take a look at what caused the outliers? Or is it necessary to fit a line without outliers? (5) The last “Cairo’s Qualities” is the same as the previous one; I assume there might be a mistake?

Altogether, interesting and persuading analyses, as well as a strong defense of your visualizations. I really enjoyed reading it!

**Comment by guangyu-liu** [comment]
I'm sorry, I just saw your document "InClassPresEdits.docx". Please ignore the fifth question above.

**Comment by dalyons3** [comment]
Thank you for your feedback! We have incorporated the suggestions into our final project.
