### ISSUE TITLE
Presentation feedback

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/viz-dalyons3#2]
* Why a strip chart over a boxplot or violin plot? They identify the summary statistics better
  * Okay, strip chart gives you the third color channel. But how is that useful?
* For the race plot, perhaps instead of a plain boxplot use a point range plot. Basically a point estimate and 95% confidence interval. If the point is to show that the Asian observations are outliers, this should still get that info across (or at least as well as a boxplot) with fewer visual features
* For the smoothing lines, you can keep the confidence intervals but adjust the color or alpha transparency so that they don't wash out all the other data points

**Comment by dalyons3** [comment]
Thank you, we've made the edits and hope you enjoy our final product.
